// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "action_t.h"

static int __action_t_hash_computed;
static uint64_t __action_t_hash;

uint64_t __action_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __action_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __action_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xb29124263942ec39LL
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __action_t_get_hash(void)
{
    if (!__action_t_hash_computed) {
        __action_t_hash = (int64_t)__action_t_hash_recursive(NULL);
        __action_t_hash_computed = 1;
    }

    return __action_t_hash;
}

int __action_t_encode_array(void *buf, int offset, int maxlen, const action_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].vel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ang_vel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int action_t_encode(void *buf, int offset, int maxlen, const action_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __action_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __action_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __action_t_encoded_array_size(const action_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __double_encoded_array_size(&(p[element].vel), 1);

        size += __double_encoded_array_size(&(p[element].ang_vel), 1);

    }
    return size;
}

int action_t_encoded_size(const action_t *p)
{
    return 8 + __action_t_encoded_array_size(p, 1);
}

int __action_t_decode_array(const void *buf, int offset, int maxlen, action_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].vel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ang_vel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __action_t_decode_array_cleanup(action_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_decode_array_cleanup(&(p[element].vel), 1);

        __double_decode_array_cleanup(&(p[element].ang_vel), 1);

    }
    return 0;
}

int action_t_decode(const void *buf, int offset, int maxlen, action_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __action_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __action_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int action_t_decode_cleanup(action_t *p)
{
    return __action_t_decode_array_cleanup(p, 1);
}

int __action_t_clone_array(const action_t *p, action_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_clone_array(&(p[element].vel), &(q[element].vel), 1);

        __double_clone_array(&(p[element].ang_vel), &(q[element].ang_vel), 1);

    }
    return 0;
}

action_t *action_t_copy(const action_t *p)
{
    action_t *q = (action_t*) malloc(sizeof(action_t));
    __action_t_clone_array(p, q, 1);
    return q;
}

void action_t_destroy(action_t *p)
{
    __action_t_decode_array_cleanup(p, 1);
    free(p);
}

int action_t_publish(lcm_t *lc, const char *channel, const action_t *p)
{
      int max_data_size = action_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = action_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _action_t_subscription_t {
    action_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void action_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    action_t p;
    memset(&p, 0, sizeof(action_t));
    status = action_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding action_t!!!\n", status);
        return;
    }

    action_t_subscription_t *h = (action_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    action_t_decode_cleanup (&p);
}

action_t_subscription_t* action_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    action_t_handler_t f, void *userdata)
{
    action_t_subscription_t *n = (action_t_subscription_t*)
                       malloc(sizeof(action_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 action_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg action_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int action_t_subscription_set_queue_capacity (action_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int action_t_unsubscribe(lcm_t *lcm, action_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe action_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

