// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "agent_t.h"

static int __agent_t_hash_computed;
static uint64_t __agent_t_hash;

uint64_t __agent_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __agent_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __agent_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x558e18ca186bed87LL
         + __boolean_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __agent_t_get_hash(void)
{
    if (!__agent_t_hash_computed) {
        __agent_t_hash = (int64_t)__agent_t_hash_recursive(NULL);
        __agent_t_hash_computed = 1;
    }

    return __agent_t_hash;
}

int __agent_t_encode_array(void *buf, int offset, int maxlen, const agent_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].is_runner), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].theta), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].vel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ang_vel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int agent_t_encode(void *buf, int offset, int maxlen, const agent_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __agent_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __agent_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __agent_t_encoded_array_size(const agent_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __boolean_encoded_array_size(&(p[element].is_runner), 1);

        size += __double_encoded_array_size(&(p[element].x), 1);

        size += __double_encoded_array_size(&(p[element].y), 1);

        size += __double_encoded_array_size(&(p[element].theta), 1);

        size += __double_encoded_array_size(&(p[element].vel), 1);

        size += __double_encoded_array_size(&(p[element].ang_vel), 1);

    }
    return size;
}

int agent_t_encoded_size(const agent_t *p)
{
    return 8 + __agent_t_encoded_array_size(p, 1);
}

int __agent_t_decode_array(const void *buf, int offset, int maxlen, agent_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].is_runner), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].theta), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].vel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ang_vel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __agent_t_decode_array_cleanup(agent_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __boolean_decode_array_cleanup(&(p[element].is_runner), 1);

        __double_decode_array_cleanup(&(p[element].x), 1);

        __double_decode_array_cleanup(&(p[element].y), 1);

        __double_decode_array_cleanup(&(p[element].theta), 1);

        __double_decode_array_cleanup(&(p[element].vel), 1);

        __double_decode_array_cleanup(&(p[element].ang_vel), 1);

    }
    return 0;
}

int agent_t_decode(const void *buf, int offset, int maxlen, agent_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __agent_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __agent_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int agent_t_decode_cleanup(agent_t *p)
{
    return __agent_t_decode_array_cleanup(p, 1);
}

int __agent_t_clone_array(const agent_t *p, agent_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __boolean_clone_array(&(p[element].is_runner), &(q[element].is_runner), 1);

        __double_clone_array(&(p[element].x), &(q[element].x), 1);

        __double_clone_array(&(p[element].y), &(q[element].y), 1);

        __double_clone_array(&(p[element].theta), &(q[element].theta), 1);

        __double_clone_array(&(p[element].vel), &(q[element].vel), 1);

        __double_clone_array(&(p[element].ang_vel), &(q[element].ang_vel), 1);

    }
    return 0;
}

agent_t *agent_t_copy(const agent_t *p)
{
    agent_t *q = (agent_t*) malloc(sizeof(agent_t));
    __agent_t_clone_array(p, q, 1);
    return q;
}

void agent_t_destroy(agent_t *p)
{
    __agent_t_decode_array_cleanup(p, 1);
    free(p);
}

int agent_t_publish(lcm_t *lc, const char *channel, const agent_t *p)
{
      int max_data_size = agent_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = agent_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _agent_t_subscription_t {
    agent_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void agent_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    agent_t p;
    memset(&p, 0, sizeof(agent_t));
    status = agent_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding agent_t!!!\n", status);
        return;
    }

    agent_t_subscription_t *h = (agent_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    agent_t_decode_cleanup (&p);
}

agent_t_subscription_t* agent_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    agent_t_handler_t f, void *userdata)
{
    agent_t_subscription_t *n = (agent_t_subscription_t*)
                       malloc(sizeof(agent_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 agent_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg agent_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int agent_t_subscription_set_queue_capacity (agent_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int agent_t_unsubscribe(lcm_t *lcm, agent_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe agent_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

