/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class agent_t implements lcm.lcm.LCMEncodable
{
    public boolean is_runner;
    public double x;
    public double y;
    public double theta;
    public double vel;
    public double ang_vel;
 
    public agent_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x558e18ca186bed87L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.agent_t.class))
            return 0L;
 
        classes.add(lcmtypes.agent_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte( this.is_runner ? 1 : 0); 
 
        outs.writeDouble(this.x); 
 
        outs.writeDouble(this.y); 
 
        outs.writeDouble(this.theta); 
 
        outs.writeDouble(this.vel); 
 
        outs.writeDouble(this.ang_vel); 
 
    }
 
    public agent_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public agent_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.agent_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.agent_t o = new lcmtypes.agent_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.is_runner = ins.readByte()!=0;
 
        this.x = ins.readDouble();
 
        this.y = ins.readDouble();
 
        this.theta = ins.readDouble();
 
        this.vel = ins.readDouble();
 
        this.ang_vel = ins.readDouble();
 
    }
 
    public lcmtypes.agent_t copy()
    {
        lcmtypes.agent_t outobj = new lcmtypes.agent_t();
        outobj.is_runner = this.is_runner;
 
        outobj.x = this.x;
 
        outobj.y = this.y;
 
        outobj.theta = this.theta;
 
        outobj.vel = this.vel;
 
        outobj.ang_vel = this.ang_vel;
 
        return outobj;
    }
 
}

