/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class reset_t implements lcm.lcm.LCMEncodable
{
    public int initial_runner_idx;
 
    public reset_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xd610df9b4fa9c514L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.reset_t.class))
            return 0L;
 
        classes.add(lcmtypes.reset_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.initial_runner_idx); 
 
    }
 
    public reset_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public reset_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.reset_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.reset_t o = new lcmtypes.reset_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.initial_runner_idx = ins.readInt();
 
    }
 
    public lcmtypes.reset_t copy()
    {
        lcmtypes.reset_t outobj = new lcmtypes.reset_t();
        outobj.initial_runner_idx = this.initial_runner_idx;
 
        return outobj;
    }
 
}

