/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class world_t implements lcm.lcm.LCMEncodable
{
    public lcmtypes.agent_t runner;
    public lcmtypes.agent_t chaser;
 
    public world_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xecb7acc198c7cbe0L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.world_t.class))
            return 0L;
 
        classes.add(lcmtypes.world_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + lcmtypes.agent_t._hashRecursive(classes)
             + lcmtypes.agent_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.runner._encodeRecursive(outs); 
 
        this.chaser._encodeRecursive(outs); 
 
    }
 
    public world_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public world_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.world_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.world_t o = new lcmtypes.world_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.runner = lcmtypes.agent_t._decodeRecursiveFactory(ins);
 
        this.chaser = lcmtypes.agent_t._decodeRecursiveFactory(ins);
 
    }
 
    public lcmtypes.world_t copy()
    {
        lcmtypes.world_t outobj = new lcmtypes.world_t();
        outobj.runner = this.runner.copy();
 
        outobj.chaser = this.chaser.copy();
 
        return outobj;
    }
 
}

